#spring.application.name=mini-ecommerce-backend
spring:
    profiles:
        active: local
    datasource:
        url: jdbc:mysql://localhost:3306/mini_ecommerce?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 654321
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

server:
    port: 8080

jwt:
    secret: "your-256-bit-secret-key-your-256-bit-secret-key"
    expire-minutes: 120